// Generated by the announcer.rb  DO NOT EDIT!!

#import "SCManagedDeviceCapacityAnalyzerListener.h"

#import <Foundation/Foundation.h>

@interface SCManagedDeviceCapacityAnalyzerListenerAnnouncer : NSObject <SCManagedDeviceCapacityAnalyzerListener>

- (void)addListener:(id<SCManagedDeviceCapacityAnalyzerListener>)listener;
- (void)removeListener:(id<SCManagedDeviceCapacityAnalyzerListener>)listener;

@end
