// 42f6113daff3eebf06d809a073c99651867c42ea
// Generated by the value-object.rb  DO NOT EDIT!!

#import "SCManagedVideoCapturerOutputType.h"

#import <AvailabilityMacros.h>

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>

@protocol SCManagedVideoCapturerOutputSettings <NSObject, NSCoding, NSCopying>

@property (nonatomic, assign, readonly) CGFloat width;

@property (nonatomic, assign, readonly) CGFloat height;

@property (nonatomic, assign, readonly) CGFloat videoBitRate;

@property (nonatomic, assign, readonly) CGFloat audioBitRate;

@property (nonatomic, assign, readonly) NSUInteger keyFrameInterval;

@property (nonatomic, assign, readonly) SCManagedVideoCapturerOutputType outputType;

@end

@interface SCManagedVideoCapturerOutputSettings : NSObject <SCManagedVideoCapturerOutputSettings>

@property (nonatomic, assign, readonly) CGFloat width;

@property (nonatomic, assign, readonly) CGFloat height;

@property (nonatomic, assign, readonly) CGFloat videoBitRate;

@property (nonatomic, assign, readonly) CGFloat audioBitRate;

@property (nonatomic, assign, readonly) NSUInteger keyFrameInterval;

@property (nonatomic, assign, readonly) SCManagedVideoCapturerOutputType outputType;

- (instancetype)initWithWidth:(CGFloat)width
                       height:(CGFloat)height
                 videoBitRate:(CGFloat)videoBitRate
                 audioBitRate:(CGFloat)audioBitRate
             keyFrameInterval:(NSUInteger)keyFrameInterval
                   outputType:(SCManagedVideoCapturerOutputType)outputType;

@end
