// 49126048c3d19dd5b676b8d39844cf133833b67a
// Generated by the value-object.rb  DO NOT EDIT!!

#import "SCManagedCapturerState.h"

#import <AvailabilityMacros.h>

#import <Foundation/Foundation.h>

@interface SCManagedCapturerStateBuilder : NSObject

+ (instancetype)withManagedCapturerState:(id<SCManagedCapturerState>)managedCapturerState;

- (SCManagedCapturerState *)build;

- (instancetype)setIsRunning:(BOOL)isRunning;

- (instancetype)setIsNightModeActive:(BOOL)isNightModeActive;

- (instancetype)setIsPortraitModeActive:(BOOL)isPortraitModeActive;

- (instancetype)setLowLightCondition:(BOOL)lowLightCondition;

- (instancetype)setAdjustingExposure:(BOOL)adjustingExposure;

- (instancetype)setDevicePosition:(SCManagedCaptureDevicePosition)devicePosition;

- (instancetype)setZoomFactor:(CGFloat)zoomFactor;

- (instancetype)setFlashSupported:(BOOL)flashSupported;

- (instancetype)setTorchSupported:(BOOL)torchSupported;

- (instancetype)setFlashActive:(BOOL)flashActive;

- (instancetype)setTorchActive:(BOOL)torchActive;

- (instancetype)setLensesActive:(BOOL)lensesActive;

- (instancetype)setArSessionActive:(BOOL)arSessionActive;

- (instancetype)setLiveVideoStreaming:(BOOL)liveVideoStreaming;

- (instancetype)setLensProcessorReady:(BOOL)lensProcessorReady;

@end
