// ed265cb0c346ae35dce70d3fc12a0bd8deae0802
// Generated by the value-object.rb  DO NOT EDIT!!

#import <AvailabilityMacros.h>

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@protocol SCManagedRecordedVideo <NSObject, NSCoding, NSCopying>

@property (nonatomic, copy, readonly) NSURL *videoURL;

@property (nonatomic, copy, readonly) NSURL *rawVideoDataFileURL;

@property (nonatomic, copy, readonly) UIImage *placeholderImage;

@property (nonatomic, assign, readonly) BOOL isFrontFacingCamera;

@end

@interface SCManagedRecordedVideo : NSObject <SCManagedRecordedVideo>

@property (nonatomic, copy, readonly) NSURL *videoURL;

@property (nonatomic, copy, readonly) NSURL *rawVideoDataFileURL;

@property (nonatomic, copy, readonly) UIImage *placeholderImage;

@property (nonatomic, assign, readonly) BOOL isFrontFacingCamera;

- (instancetype)initWithVideoURL:(NSURL *)videoURL
             rawVideoDataFileURL:(NSURL *)rawVideoDataFileURL
                placeholderImage:(UIImage *)placeholderImage
             isFrontFacingCamera:(BOOL)isFrontFacingCamera;

@end
