// Generated by the announcer.rb  DO NOT EDIT!!

#import "SCManagedCapturerListener.h"

#import <Foundation/Foundation.h>

@interface SCManagedCapturerListenerAnnouncer : NSObject <SCManagedCapturerListener>

- (BOOL)addListener:(id<SCManagedCapturerListener>)listener;
- (void)removeListener:(id<SCManagedCapturerListener>)listener;

@end
